server:
  port: 8000
  error:
    include-stacktrace: never
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:mysql://localhost/cambio_service
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs


