server:
  port: 8100
  error:
    include-stacktrace: never
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
resilience4j:
  bulkhead:
    instances:
      foo-bar:
        maxConcurrentCalls: 2
  ratelimiter:
    instances:
      foo-bar:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  retry:
    instances:
      foo-bar:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost/book_service
    username: root
    password: mysql
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs